name: Flake8 Check

on: [push,pull_request]

jobs:
 flake8-chek:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Set up Python
    uses: actions/setup-python@v2
    with:
     python-version: .x

  - name: Install dependencies
    run:
       python -m pip install --upgrade pip
       pip install flake8
  - name: Run flake8
    run: |
       flake8 .
